apiVersion: v1

kind: Pod

metadata:
  name: myapp-pod
  labels:
   app: myapp
   costcenter: amer
   location: NA

spec:
    containers:
        - name: nginx-container
          image: nginx
        - name: backend-container
          image: redis


